In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
import os
for dirname, _, filenames in os.walk('ParticipantData_BTPC/'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

ParticipantData_BTPC/.DS_Store
ParticipantData_BTPC/Sample Submission.csv
ParticipantData_BTPC/Test.csv
ParticipantData_BTPC/Train.csv


In [3]:
data = pd.read_csv('ParticipantData_BTPC/Train.csv')
data.head()

session_id  session_number  \
0  57f879e70d3c5fc2a98102d64c9fd84e             715   
1  a5442b0c7c33d0a811e7661e556b2de8              55   
2  305cb1486ed8610c00b37007926cb2c4              11   
3  f2c1ecc9993f0071df91ba178450498c            2794   
4  e460830ae295e55d2216ebdc761ab9a6            3674   

                                        client_agent      device_details  \
0  Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...    Desktop - Chrome   
1                           Product/8.0 iPhone/8.1.3        iPhone - iOS   
2  Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_2 like ...  iPhone - MobileWeb   
3  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...        Desktop - IE   
4  Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_1 like ...        iPhone - Web   

         date  purchased  added_in_cart  checked_out  time_spent  
0  2020-01-22          1              0            0     236.886  
1  2020-02-27          1              0            0    1277.455  
2  2019-08-01          0              0            0      21.704  
3  2019-12-30          0              1            0     455.201  
4  2019-09-10          0              0            0    1164.877

In [4]:
data = data.drop(['session_id','session_number','client_agent','device_details'], axis=1)
data.head()

date  purchased  added_in_cart  checked_out  time_spent
0  2020-01-22          1              0            0     236.886
1  2020-02-27          1              0            0    1277.455
2  2019-08-01          0              0            0      21.704
3  2019-12-30          0              1            0     455.201
4  2019-09-10          0              0            0    1164.877

In [5]:
dates = data['date'].values
dat = pd.to_datetime(dates)

data['Month'] = dat.strftime("%m")
data['Year'] = dat.strftime("%Y")
data.head()

date  purchased  added_in_cart  checked_out  time_spent Month  Year
0  2020-01-22          1              0            0     236.886    01  2020
1  2020-02-27          1              0            0    1277.455    02  2020
2  2019-08-01          0              0            0      21.704    08  2019
3  2019-12-30          0              1            0     455.201    12  2019
4  2019-09-10          0              0            0    1164.877    09  2019

In [6]:
d = pd.to_datetime(data['date'])
data['dayofWeek'] = d.dt.day_name()
data.head()

date  purchased  added_in_cart  checked_out  time_spent Month  Year  \
0  2020-01-22          1              0            0     236.886    01  2020   
1  2020-02-27          1              0            0    1277.455    02  2020   
2  2019-08-01          0              0            0      21.704    08  2019   
3  2019-12-30          0              1            0     455.201    12  2019   
4  2019-09-10          0              0            0    1164.877    09  2019   

   dayofWeek  
0  Wednesday  
1   Thursday  
2   Thursday  
3     Monday  
4    Tuesday

In [7]:
data['dayofWeek'] = data['dayofWeek'].map({'Monday':1,'Tuesday':2,'Wednesday':3,'Thursday':4,
                                           'Friday':5, 'Saturday':6,'Sunday':7})
data.head()

date  purchased  added_in_cart  checked_out  time_spent Month  Year  \
0  2020-01-22          1              0            0     236.886    01  2020   
1  2020-02-27          1              0            0    1277.455    02  2020   
2  2019-08-01          0              0            0      21.704    08  2019   
3  2019-12-30          0              1            0     455.201    12  2019   
4  2019-09-10          0              0            0    1164.877    09  2019   

   dayofWeek  
0          3  
1          4  
2          4  
3          1  
4          2

In [8]:
data = data.drop(['date'], axis=1)
data.head()

purchased  added_in_cart  checked_out  time_spent Month  Year  dayofWeek
0          1              0            0     236.886    01  2020          3
1          1              0            0    1277.455    02  2020          4
2          0              0            0      21.704    08  2019          4
3          0              1            0     455.201    12  2019          1
4          0              0            0    1164.877    09  2019          2

In [9]:
x = data.drop(['time_spent'], axis=1)
y = data['time_spent']

In [10]:
model = LinearRegression()

In [11]:
model.fit(x,y)

LinearRegression()

In [12]:
y_pred = model.predict(x)

In [13]:
y_pred

array([1099.13984015, 1077.09060231,  458.14813921, ...,  447.25965355,
        502.24661489,  386.82844937])

In [14]:
target = y.values

In [15]:
model.get_params(deep=True)

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'normalize': 'deprecated',
 'positive': False}

In [16]:
model.intercept_

790324.7730639762

In [17]:
model.coef_

array([ 845.10017938,  857.31928523, 1146.9923745 ,  -27.49348067,
       -391.11860032,    5.44424283])

In [18]:
from sklearn.metrics import r2_score

In [19]:
r2_score(target, y_pred)

0.09107461480984913

In [21]:
test = pd.read_csv('ParticipantData_BTPC/Test.csv')
test

session_id  session_number  \
0     0bf72b05b2cf70dc5e28c3c09f9c4f97              99   
1     6bc696d99954e4f1367e845465186aef             935   
2     3d8611a5ea0f621d205b67f09f663a89             902   
3     a0351545c032fd0da36289410c6c3354            3223   
4     dd8999772b0ab27225fb05e5df2f1da6             231   
...                                ...             ...   
2322  a7ce384215acf0a0efe8e6152d6e0af3            1375   
2323  627898fc1c329846956412487ca617b3            1617   
2324  f642380795f4b57ffac8b5c4d6556765            4433   
2325  298c00625e7ffef797745a866b898d3c             297   
2326  22cf6e64666061ebb3442b5c83013cdd             880   

                                           client_agent  \
0     Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7....   
1     Product/160393 Android/4.3 Device/samsung_GT-I...   
2                            Product/4.2.2 iPhone/7.1.2   
3     Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   
4     Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKi...   
...                                                 ...   
2322       Product/244 CFNetwork/711.1.12 Darwin/14.0.0   
2323  Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...   
2324                         Product/4.7.0 iPhone/8.1.2   
2325                             Product/4.2.2 iPad/8.0   
2326  Product/160432 Android/5.0 Device/LGE_LG-D855 ...   

               device_details        date  purchased  added_in_cart  \
0                Desktop - IE  2020-01-07          1              0   
1     Android Phone - Android  2020-02-13          0              0   
2                iPhone - iOS  2019-10-14          1              0   
3                Desktop - IE  2020-01-26          0              0   
4            Desktop - Chrome  2020-01-29          0              0   
...                       ...         ...        ...            ...   
2322            Other - Other  2019-11-06          0              0   
2323         Desktop - Chrome  2020-01-18          0              1   
2324             iPhone - iOS  2020-01-14          0              0   
2325               iPad - iOS  2019-10-01          1              0   
2326  Android Phone - Android  2020-02-22          0              1   

      checked_out  
0               0  
1               0  
2               0  
3               0  
4               0  
...           ...  
2322            0  
2323            0  
2324            0  
2325            0  
2326            0  

[2327 rows x 8 columns]

In [22]:
test = test.drop(['session_id','session_number','client_agent','device_details'], axis=1)

datess = test['date'].values
dats = pd.to_datetime(datess)

test['Month'] = dats.strftime("%m")
test['Year'] = dats.strftime("%Y")

ds = pd.to_datetime(test['date'])
test['dayofWeek'] = ds.dt.day_name()

test['dayofWeek'] = test['dayofWeek'].map({'Monday':1,'Tuesday':2,'Wednesday':3,'Thursday':4,
                                           'Friday':5, 'Saturday':6,'Sunday':7})

test = test.drop(['date'], axis=1)
test.head()

purchased  added_in_cart  checked_out Month  Year  dayofWeek
0          1              0            0    01  2020          2
1          0              0            0    02  2020          4
2          1              0            0    10  2019          1
3          0              0            0    01  2020          7
4          0              0            0    01  2020          3

In [23]:
model.predict(test)

array([1093.69559732,  231.99042293, 1231.92862875, ...,  248.59541794,
       1237.37287159, 1100.19819383])

In [29]:
predictions = model.predict(test)

df = pd.DataFrame(data = predictions, columns=['time_spent'])

df.to_csv('ParticipantData_BTPC/submission.csv',index=False)

In [30]:
s1 = pd.read_csv('ParticipantData_BTPC/submission.csv')

In [31]:
s2 = pd.read_csv('ParticipantData_BTPC/Sample Submission.csv')